### ISSUE TITLE
No Captcha at Login

### ISSUE THREAD

**Issue by kaesspaetzle** [superturboryan/WatchCloud-Privacy-Policy#1]
On Apple Watch Ultra 2 with latest WatchOS I am stuck at the login screen. I set my e-mail and password with my existing SoundCloud account, but no captcha shows up on the watch.

![incoming-17E1D514-1968-4014-9083-7D77CA567D4E](https://github.com/superturboryan/WatchCloud-Privacy-Policy/assets/76078658/ecc80877-cd47-429c-aa69-120f7ec61c2a)
![incoming-2D941BA0-CC22-4E91-9B59-BBB6C2882638](https://github.com/superturboryan/WatchCloud-Privacy-Policy/assets/76078658/804c9ce0-6768-4924-aa1a-e4409c95b259)
![incoming-36F83056-77DC-4AE2-AF63-8A3A54E2322E](https://github.com/superturboryan/WatchCloud-Privacy-Policy/assets/76078658/d2636408-53c2-4ab3-b46b-b9caff79e450)

**Comment by superturboryan** [comment]
Using "Sign in with Google" **sometimes requires me to enter my email twice** before being asked to enter my password, but I can confirm that it does work:
<br />
<img src="https://i.imgur.com/cxTSthr.gif">

**Comment by kaesspaetzle** [comment]
Thank you for your reply.

Now it works. But a had to do some additional steps. I have to different emails in Soundcloud.

- Add my Google-Mail to my Soundcloudaccount.
- Logout on the desktop on Soundcloud.
- Login with my now registered Google login into Soundcloud.
- The only 2FA that works on the watch was the one with the 6 digits. 
- Now I can use your App.

- Login with Apple or my regulary used E-Mail doesn't work.

**Comment by superturboryan** [comment]
Thanks for sharing the additional steps you took to make it work!

**Comment by kaesspaetzle** [comment]
No Problem.

It is important to use Google login first in the desktop app. It deosn't work with your gmail adress only. Soundcloud answers with an error message on the watch.

short (if you use 2FA):

- google log in at soundclound on the desktop 
- google log in on the watch
- 2FA with 6 digit code and google authenticator
- now your app must work.

Does your App work on the go without my iPhone? So I can stream my playlist during my evening walks.That will be great and usefull. Haven't tried it so far.

**Comment by superturboryan** [comment]
It should work as long as the watch has an internet connection. 
I originally built the app so that I could listen to SoundCloud while out running without having to carry my phone.

**Comment by drbishop76** [comment]
Hi there — I tried the above steps without success. When I enter my google email via the google login option of the app it produces a “something went wrong” error. Consistently, no matter if I login via google on the desktop beforehand or not. Facebook is also another dead end as is the apple sign in option. Wondering if you have any suggestions in the meantime while you fix the captcha bug issue? Thanks and trul7 appreciate your effort on this. It’s basically the reason why I’ve decided to keep the watch. If I hadn’t found your app (even if still in development) I would’ve returned the thing as I primarily use SoundCloud.

**Comment by kaesspaetzle** [comment]
Hi.

I have entered my googlemail as an additional E-Mailadress in SoundCloud AND as google Login on my Desktopbrowser. And I set it es my primary adress. After that, I have to log out in SoundCloud first. Then I log in with Google Log in.

The tricky part was the 2factor Authentication that I am using on my Google Account. The only way that works was via Google Authenticator on the iPhone. All solutions with Captcha, etc doesn‘t work. The needed picture don‘t show up on the Watch. It is the menu called something with „entering 6 digits to use Google Log in“.

It is easier without 2FA. But that isn‘t a solution for me (security). And you have to set up Google Authenticator first, bevor trying to log in into SoundCloud at the Watch.

By the way. The App works on the go with my provider here in Germany (Telekom). iPhone at home and Streaming via LTE on the watch. It is great. But some Mixes don‘t start and you cannot resume a stopped play sometimes. It ends in an endless loading and the music never starts. Don‘t know, if the longer mixes and larger soundfiles are the problem. 
My solution is to load another playlist / soundmix,

**Comment by ard9000** [comment]
> Hi there — I tried the above steps without success. When I enter my google email via the google login option of the app it produces a “something went wrong” error. Consistently, no matter if I login via google on the desktop beforehand or not. Facebook is also another dead end as is the apple sign in option. Wondering if you have any suggestions in the meantime while you fix the captcha bug issue? Thanks, and truly appreciate your effort! It’s basically the reason why I’ve decided to keep the watch. If I hadn’t found your app (even if still in development) I would’ve returned the thing as I primarily use SoundCloud.

I had the same issues. Using Google login, I would randomly get the "something went wrong" message at the point of either entering my email or password. I just brute force kept trying until it worked, it took about 7 tries. 

Thanks for a great app, I can't believe I have Soundcloud on my Apple Watch Ultra again! But the login definitely needs some work.

**Comment by superturboryan** [comment]
#### Version 1.3.0 adds an iOS companion app that allows for connecting to SoundCloud using the phone's browser. 

All login methods (Google, FB, Apple ID) work with the iOS app 🥳

![Screenshot 2023-12-16 at 08 22 18](https://github.com/superturboryan/WatchCloud-Privacy-Policy/assets/45875515/89fe24cd-4029-4da3-8f47-59157c3e65a1)

**Comment by kaesspaetzle** [comment]
Updated!

It works.

AppleWatch 4 & Ultra 2 - both with WatchOS 10.2 Public Beta 1. iPhone 13 Pro Max with iOS 17.2 Public Beta 1.

**Comment by mgjsn** [comment]
I want to listen offline without my phone and i dont have lte, if i get soundcloud+ will it work through draftcloud?

**Comment by mgjsn** [comment]
Also do my playlists not update on watchcloud because i've added songs to my playlists on soundcloud but they aren't showing on watchcloud. Thanks

**Comment by superturboryan** [comment]
Version 1.3.2 uses the updated SoundCloud authentication endpoint (`secure.soundcloud.com`) and there isn't any captcha verification on the watch browser anymore 🥳
